[package]
name = "fds-language-server"
version = "1.0.0"
edition = "2021"


[dependencies]
serde_json = "1.0.87"
tower-lsp = "0.17.0"
anyhow = "1.0.66"
tokio = { version = "1.21.2", features = ["full"] }
ropey = "1.5.0"
dashmap = "5.4.0"
chumsky = "0.8.0"
